version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      python-dependencies:
        # A pattern can be...
        patterns:
        - '*'
- package-ecosystem: github-actions
  directory: ".github/"
  schedule:
    interval: weekly
